import type { NextConfig } from 'next';

const securityHeaders = [
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'X-DNS-Prefetch-Control', value: 'on' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload',
  },
  {
    key: 'Content-Security-Policy',
    value: [
      "default-src 'self'",
      "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data: blob: https:",
      "font-src 'self' data:",
      "connect-src 'self' https:",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
    ].join('; '),
  },
];

const nextConfig: NextConfig = {
  poweredByHeader: false,
  reactStrictMode: true,
  // These packages ship runtime assets (WASM, native bindings, CJS entrypoints)
  // that must be require()d by Node instead of inlined by the bundler.
  serverExternalPackages: [
    '@electric-sql/pglite',
    'drizzle-orm',
    'postgres',
    'bcryptjs',
    '@vercel/blob',
  ],
  // Tailwind CSS v4 must be compiled by its own Turbopack loader; without it
  // `@theme` / `@utility` at-rules are passed through untouched.
  turbopack: {
    rules: {
      '*.css': {
        loaders: ['@tailwindcss/turbopack'],
        as: '*.css',
      },
    },
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '**.public.blob.vercel-storage.com' },
      { protocol: 'https', hostname: 'blob.vercel-storage.com' },
      { protocol: 'https', hostname: '**.vercel-storage.com' },
    ],
    localPatterns: [
      { pathname: '/logo.jpg', search: '' },
      { pathname: '/uploads/**', search: '' },
      { pathname: '/placeholders/**', search: '' },
    ],
    formats: ['image/avif', 'image/webp'],
    qualities: [50, 75, 90],
    // Seeded demo artwork ships as SVG (generated by `npm run db:seed`).
    // Real uploads are restricted to JPEG/PNG/WebP/GIF/AVIF by the server.
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; style-src 'unsafe-inline';",
  },
  async headers() {
    return [{ source: '/:path*', headers: securityHeaders }];
  },
};

export default nextConfig;
